name: Build and Deploy

on:
  push:
    branches:
      - main # Trigger on push to the main branch
  workflow_dispatch: # Allow manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Grant write permissions to the GITHUB_TOKEN

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Use the Node.js version your app requires

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: List files in workspace (debugging)
        run: ls -R

      - name: Get the last commit message from main branch
        id: get_commit_msg
        run: |
          # Fetch the latest commit message from the main branch
          COMMIT_MESSAGE=$(git log -1 --pretty=%B origin/main)
          echo "commit_message=$COMMIT_MESSAGE" >> $GITHUB_ENV

      - name: Deploy to deploy branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout --orphan deploy
          git rm -rf .  # Remove all files from repo
          mv dist/* .   # Move build files to root
          rm -rf dist   # Delete dist folder after moving contents
          echo "node_modules" > .gitignore  # Ensure node_modules is ignored
          git add .  # Add all files in root
          # Use the commit message from the previous step and format it
          git commit -m "Deploy of '${{ env.commit_message }}'"
          git push origin deploy --force
